using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using System.Windows.Resources;

[assembly: AssemblyAssociatedContentFile("offsets.json")]
[assembly: AssemblyAssociatedContentFile("recipes.json")]
[assembly: AssemblyCompany("PoE2ExpeditionScanner")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0+c2f2f05f42558e1b3b8e430121149b9cc2324950")]
[assembly: AssemblyProduct("PoE2ExpeditionScanner")]
[assembly: AssemblyTitle("PoE2ExpeditionScanner")]
[assembly: TargetPlatform("Windows7.0")]
[assembly: SupportedOSPlatform("Windows7.0")]
[assembly: AssemblyVersion("1.0.0.0")]
